name: Merge pull request to main and deploy

on:
  pull_request:
    types: [closed]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your validation steps here (e.g., tests)

      - name: Merge pull request
        uses: pullreminders/merge@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          method: merge

  deploy:
    runs-on: ubuntu-latest
    needs: merge
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
